-- Get interesection between tutor_id y carrera_id
SELECT
    numrange(
        (
            SELECT
                MIN(tutor_id)
            FROM
                platzi.alumnos
        ),
        (
            SELECT
                MAX(tutor_id)
            FROM
                platzi.alumnos
        )
    ) * numrange(
        (
            SELECT
                MIN(carrera_id)
            FROM
                platzi.alumnos
        ),
        (
            SELECT
                MAX(carrera_id)
            FROM
                platzi.alumnos
        )
    );